{{- if or .Values.dash.secrets.external.enabled .Values.postgres.secrets.external.enabled -}}
{{- if .Values.dash.secrets.external.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "dash.fullname" . }}-dash-secrets
  labels:
    {{- include "dash.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.dash.secrets.external.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.dash.secrets.external.secretStoreRef.kind | quote }}
    name: {{ .Values.dash.secrets.external.secretStoreRef.name | quote }}
  target:
    name: {{ .Values.dash.secrets.name | quote }}
    creationPolicy: Owner
  data:
    {{- if .Values.dash.secrets.external.data }}
    {{- toYaml .Values.dash.secrets.external.data | nindent 4 }}
    {{- else }}
    []
    {{- end }}
---
{{- end }}
{{- if and .Values.postgres.enabled .Values.postgres.secrets.external.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "dash.fullname" . }}-postgres-secrets
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  refreshInterval: {{ .Values.postgres.secrets.external.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.postgres.secrets.external.secretStoreRef.kind | quote }}
    name: {{ .Values.postgres.secrets.external.secretStoreRef.name | quote }}
  target:
    name: {{ .Values.postgres.secrets.name | quote }}
    creationPolicy: Owner
  data:
    {{- if .Values.postgres.secrets.external.data }}
    {{- toYaml .Values.postgres.secrets.external.data | nindent 4 }}
    {{- else }}
    []
    {{- end }}
{{- end }}
{{- end }}
