{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dash.postgres.fullname" . }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "dash.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
