{{- if or .Values.dash.secrets.blueprint.enabled .Values.postgres.secrets.blueprint.enabled -}}
{{- include "dash.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dash.secrets.name | quote }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.postgres.enabled }}
  {{ .Values.dash.secrets.keys.databaseUrl }}: "REPLACE_ME"
  {{- end }}
  {{- if .Values.postgres.enabled }}
  {{ .Values.dash.secrets.keys.postgresPassword }}: "REPLACE_ME"
  {{- end }}
  {{ .Values.dash.secrets.keys.oidcClientSecret }}: "REPLACE_ME"
  {{ .Values.dash.secrets.keys.oidcCookieHashKey }}: "REPLACE_ME"
  {{ .Values.dash.secrets.keys.oidcCookieBlockKey }}: "REPLACE_ME"
{{- end }}
