{{- if or .Values.dash.secrets.blueprint.enabled .Values.postgres.secrets.blueprint.enabled -}}
{{- if .Values.dash.secrets.blueprint.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dash.secrets.name | quote }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.dash.secrets.keys.databaseUrl }}: "REPLACE_ME"
  {{ .Values.dash.secrets.keys.oidcClientSecret }}: "REPLACE_ME"
  {{ .Values.dash.secrets.keys.oidcCookieHashKey }}: "REPLACE_ME"
  {{ .Values.dash.secrets.keys.oidcCookieBlockKey }}: "REPLACE_ME"
---
{{- end }}
{{- if and .Values.postgres.enabled .Values.postgres.secrets.blueprint.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secrets.name | quote }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  {{ .Values.postgres.secrets.keys.password }}: "REPLACE_ME"
{{- end }}
{{- end }}
