name: Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set build info
        id: info
        run: |
          echo "commit=$(echo '${{ github.sha }}' | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Login
        run: echo "${{ secrets.FORGEJO_PACKAGE }}" | docker login git.at.oechsler.it -u ${{ github.actor }} --password-stdin

      - name: Build & push
        run: |
          docker build \
            --file docker/Dockerfile \
            --build-arg VERSION=${{ steps.info.outputs.version }} \
            --build-arg COMMIT=${{ steps.info.outputs.commit }} \
            --build-arg BUILD_DATE=${{ steps.info.outputs.build_date }} \
            --build-arg REPO_URL=https://git.at.oechsler.it/samuel/dash \
            --tag git.at.oechsler.it/samuel/dash:${{ github.ref_name }} \
            .
          docker push git.at.oechsler.it/samuel/dash:${{ github.ref_name }}
