package repo

import (
	"context"
	"errors"
	"time"

	domainrepo "git.at.oechsler.it/samuel/dash/v2/domain/repo"
	"git.at.oechsler.it/samuel/dash/v2/infra/persistence/model"

	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var _ domainrepo.IdpLinkRepository = (*GormIdpLinkRepo)(nil)

// idpLinkNamespace is a fixed UUID used as the namespace input to the UUID v5
// algorithm. It does NOT contribute to uniqueness — that comes from the
// (issuer, sub) pair itself, which is globally unique by the OIDC spec (sub is
// unique within an issuer, and an issuer URL is a globally unique identifier).
// The namespace is simply a required parameter of UUID v5 (SHA-1 based); we use
// an application-specific constant so our UUIDs are clearly scoped and don't
// accidentally collide with UUIDs generated by other systems using the same input.
var idpLinkNamespace = uuid.MustParse("a3d5e7f9-1b2c-4d6e-8f0a-9b1c3d5e7f90")

// deriveUserID returns a deterministic, fixed-length UUID v5 from an OIDC
// (issuer, sub) pair. Using UUID format keeps user IDs consistent in length and
// compatible with systems that expect UUID-shaped identifiers.
func deriveUserID(issuer, sub string) string {
	return uuid.NewSHA1(idpLinkNamespace, []byte(issuer+"\x00"+sub)).String()
}

type GormIdpLinkRepo struct {
	db       *gorm.DB
	userRepo *GormUserRepo
}

func NewGormIdpLinkRepo(db *gorm.DB, userRepo *GormUserRepo) (*GormIdpLinkRepo, error) {
	if err := db.AutoMigrate(&model.IdpLink{}); err != nil {
		return nil, err
	}
	return &GormIdpLinkRepo{db: db, userRepo: userRepo}, nil
}

// ResolveOrCreate looks up the internal UserID for (issuer, sub).
// If not found, creates a new link with a UUID v5 derived from (issuer, sub)
// and returns isNew=true. The caller should then run MigrateUserID(sub, userID)
// to move any pre-existing data stored under sub to the new UUID.
func (r *GormIdpLinkRepo) ResolveOrCreate(ctx context.Context, issuer, sub string) (string, bool, error) {
	var link model.IdpLink
	err := r.db.WithContext(ctx).
		Where("issuer = ? AND sub = ?", issuer, sub).
		First(&link).Error
	if err == nil {
		return link.UserID, false, nil
	}
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		return "", false, err
	}

	userID := deriveUserID(issuer, sub)

	// Ensure the users row exists before creating the idp_link — the FK
	// constraint requires the parent to be present first.
	if err := r.userRepo.EnsureExists(ctx, userID); err != nil {
		return "", false, err
	}

	newLink := model.IdpLink{
		UserID:    userID,
		Issuer:    issuer,
		Sub:       sub,
		IsPrimary: true,
		LinkedAt:  time.Now(),
	}
	if err := r.db.WithContext(ctx).
		Clauses(clause.OnConflict{DoNothing: true}).
		Create(&newLink).Error; err != nil {
		return "", false, err
	}
	return userID, true, nil
}

func (r *GormIdpLinkRepo) DeleteByUserID(ctx context.Context, userID string) error {
	return r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Delete(&model.IdpLink{}).Error
}
