services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: dash-oauth-proxy
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:3001/session/login/callback"
      OAUTH2_PROXY_WHITELIST_DOMAINS: "localhost:3001,id.at.oechsler.it"

      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "Oechsler ID"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://id.at.oechsler.it"
      OAUTH2_PROXY_CLIENT_ID: "a7d6c62a-4133-45b0-b4df-1d637ffd3a93"
      OAUTH2_PROXY_CLIENT_SECRET: "HFPVggYNjjdIHdgUAKWccsDfn0xpxhHF"
      OAUTH2_PROXY_SCOPE: "openid profile email groups"
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"

      OAUTH2_PROXY_EMAIL_DOMAINS: "*"

      OAUTH2_PROXY_COOKIE_DOMAIN: "localhost"
      OAUTH2_PROXY_COOKIE_NAME: "_dash"
      OAUTH2_PROXY_COOKIE_SECRET: "5Egal!F6!lTNB!tZml!Ei19V"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"

  caddy:
    image: caddy:latest
    container_name: dash-caddy
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - oauth2-proxy
    extra_hosts:
      - "host:host-gateway"