services:
  dash:
    # Uncomment the following lines to build the image locally
    # instead of pulling from registry
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    image: ghcr.io/oechsler/dash:latest
    container_name: dash
    restart: unless-stopped
    volumes:
      - dash_data:/data:rw
  
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: dash-oauth-proxy
    restart: unless-stopped
    depends_on:
      - dash
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REDIRECT_URL: "<OAUTH_REDIRECT_URL>"
      OAUTH2_PROXY_WHITELIST_DOMAINS: "<OAUTH_WHITELISTED_DOMAINS>"

      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "<OAUTH_PROVIDER_NAME>"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "<OAUTH_ISSUER_URL>"
      OAUTH2_PROXY_CLIENT_ID: "<OAUTH_CLIENT_ID>"
      OAUTH2_PROXY_CLIENT_SECRET: "<OAUTH_CLIENT_SECRET>"
      OAUTH2_PROXY_SCOPE: "openid profile email groups"
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"

      OAUTH2_PROXY_EMAIL_DOMAINS: "*"

      OAUTH2_PROXY_COOKIE_DOMAIN: "<COOKIE_DOMAIN>"
      OAUTH2_PROXY_COOKIE_NAME: "_dash"
      OAUTH2_PROXY_COOKIE_SECRET: "<COOKIE_SECRET>"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"

  caddy:
    image: caddy:latest
    container_name: dash-caddy
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - dash
      - oauth2-proxy

volumes:
  dash_data: