// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type DashboardEditInput struct {
	EditMode    bool
	IsAdmin     bool
	WithTrigger bool
}

func DashboardEdit(input DashboardEditInput) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div hx-swap=\"outerHTML\" id=\"edit-toggle\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if input.EditMode {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"w-12 h-12 rounded-xl bg-primary p-0 shadow-xl\"><button class=\"w-full h-full text-2xl text-primary bg-tertiary/80 rounded-xl flex items-center justify-center hover:bg-tertiary transition-colors duration-200 cursor-pointer\" hx-get=\"/dashboard/edit/off\" hx-target=\"#edit-toggle\" hx-swap=\"outerHTML\"><span class=\"material-icons-round\">done</span></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
				if input.IsAdmin {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<section id=\"apps\" hx-swap-oob=\"outerHTML\" class=\"mt-12 lg:mt-16\"><div id=\"apps-title\"></div><ul id=\"apps-list\" class=\"space-y-2 md:space-y-0 md:grid md:grid-cols-2 lg:grid-cols-4 md:grid-rows-2 md:auto-rows-fr md:grid-flow-row-dense items-stretch content-stretch gap-2\"></ul></section><div hx-get=\"/dashboard/title/applications/edit\" hx-trigger=\"load\" hx-target=\"#apps-title\" hx-swap=\"outerHTML\"></div><div hx-get=\"/applications/edit\" hx-trigger=\"load\" hx-target=\"#apps-list\" hx-swap=\"innerHTML\"></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <div hx-get=\"/categories/shelved/edit\" hx-trigger=\"load\" hx-target=\"#shelved-sections\" hx-swap=\"innerHTML\"></div><div hx-get=\"/dashboard/title/bookmarks/edit\" hx-trigger=\"load\" hx-target=\"#bookmarks-title\" hx-swap=\"outerHTML\"></div><div hx-get=\"/categories/edit\" hx-trigger=\"load\" hx-target=\"#categories-list\" hx-swap=\"innerHTML\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"w-12 h-12 rounded-xl bg-primary p-0 shadow-xl\"><button class=\"w-full h-full text-2xl text-tertiary bg-tertiary/10 rounded-xl flex items-center justify-center hover:bg-tertiary/20 transition-colors duration-200 cursor-pointer\" hx-get=\"/dashboard/edit/on\" hx-target=\"#edit-toggle\" hx-swap=\"outerHTML\"><span class=\"material-icons-round\">edit</span></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if input.WithTrigger {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div hx-get=\"/dashboard/title/applications\" hx-trigger=\"load\" hx-target=\"#apps-title\" hx-swap=\"outerHTML\"></div><div hx-get=\"/applications\" hx-trigger=\"load\" hx-target=\"#apps-list\" hx-swap=\"innerHTML\"></div><div hx-get=\"/categories/shelved\" hx-trigger=\"load\" hx-target=\"#shelved-sections\" hx-swap=\"innerHTML\"></div><div hx-get=\"/dashboard/title/bookmarks\" hx-trigger=\"load\" hx-target=\"#bookmarks-title\" hx-swap=\"outerHTML\"></div><div hx-get=\"/categories\" hx-trigger=\"load\" hx-target=\"#categories-list\" hx-swap=\"innerHTML\"></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
