name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          TEMPL_VERSION=$(grep 'github.com/a-h/templ ' go.mod | awk '{print $2}')
          go install github.com/a-h/templ/cmd/templ@${TEMPL_VERSION}
          go generate ./delivery/web/templ
          go generate ./delivery/web/static
          rm -f ./delivery/web/static/generate.go
          CGO_ENABLED=0 go build ./...
